[package]
name = "FinSc-Cosmology"
version = "0.3.2"
ipkg = "FinSc-Cosmology.ipkg"

[custom.all.FinSc-Multiset-Core]
type = "local"
path = "../FinSc-Multiset-Core"
ipkg = "FinSc-Multiset-Core.ipkg"

[custom.all.FinSc-Multiset-Transform]
type = "local"
path = "../FinSc-Multiset-Transform"
ipkg = "FinSc-Multiset-Transform.ipkg"

[custom.all.FinSc-Geometry]
type = "local"
path = "../FinSc-Geometry"
ipkg = "FinSc-Geometry.ipkg"

[custom.all.FinSc-Thermodynamics]
type = "local"
path = "../FinSc-Thermodynamics"
ipkg = "FinSc-Thermodynamics.ipkg"
